services:
  postgres17:
    image: postgres:17.5
    container_name: postgres17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres   # 用户名
      POSTGRES_PASSWORD: asd    # 密码
      POSTGRES_DB: postgres     # 默认数据库名
    volumes:
      - postgres17-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres17-data: