services:
  mysql8.0:
    image: mysql:8.0.22
    container_name: mysql8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --default-authentication-plugin=mysql_native_password
      - --lower_case_table_names=1

volumes:
  mysql_data: