version: "3"

services:
  ### hadoop 单节点 start

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env

  ### hadoop 单节点 end

  ### hive start

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    depends_on:
      - namenode
      - datanode
      - hive-metastore-db
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_HOST: hive-metastore
      HIVE_DB_NAME: metastore
      HIVE_DB_USER: hive
      HIVE_DB_PASSWORD: hive
      HIVE_DB_HOST: hive-metastore-db
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-db:5432"
    ports:
      - "9083:9083"
    env_file:
      - ./hadoop.env

  hive-metastore-db:
    image: postgres:13
    container_name: hive-metastore-db
    restart: always
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - hive_metastore_db:/var/lib/postgresql/data

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    restart: always
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000"  # JDBC
      - "10002:10002"  # Beeline Web UI
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_HOST: hive-metastore
      HIVE_DB_NAME: metastore
      HIVE_DB_USER: hive
      HIVE_DB_PASSWORD: hive
      HIVE_DB_HOST: hive-metastore-db
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore:9083"
    env_file:
      - ./hadoop.env


  ### hive end

  ### spark start

  ### spark end

  ### hbase start

  ### hbase end

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hive_metastore_db:


