services:
  nacos:
    image: nacos/nacos-server:v3.0.2
    container_name: nacos
    env_file:
      - ./env/nacos-standalone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "9080:8080"
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: mysql:8.0.22
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d/
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

