version: "3.9"

services:
  llamafactory:
    image: hiyouga/llamafactory:latest
    container_name: llamafactory
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
      - TZ=Asia/Shanghai
    command: >
      python -m src.llamafactory.cli webui
      --host 0.0.0.0
      --port 7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    volumes:
      # 覆盖系统自带的 dataset_info.json
      - ./data/dataset_info.json:/app/data/dataset_info.json
      # 本地 datasets 目录
      - ./data/datasets:/app/data/datasets
      # 模型缓存目录（持久化到宿主机）
      - ./hf_cache:/root/.cache/huggingface
      - ./exported_models:/app/exported_models
